apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodeploy
  namespace: dev
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mongocon
        image: westuser/spring-boot-mongo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  namespace: dev
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
